import { ArrowDownUp, Clock3, Target, Trophy } from "lucide-react"
import { useApp } from "@/app/app-state"
import { formatElapsedMs } from "@/lib/format"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { StatCard } from "@/components/stat-card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

export function StatisticsPage() {
  const { statistics } = useApp()
  const { general } = statistics
  return <div className="flex flex-col gap-7"><section><p className="text-sm font-medium text-muted-foreground">Evidencia de tu práctica</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Estadísticas</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Detecta dónde pierdes precisión, cuánto tardas y qué preguntas ya dominaste.</p></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Precisión" value={`${general.accuracy}%`} detail={`${general.correct} aciertos · ${general.incorrect} fallos`} icon={Target} /><StatCard label="Mediana" value={formatElapsedMs(general.medianResponseTimeMs)} detail={`Promedio ${formatElapsedMs(general.averageResponseTimeMs)}`} icon={Clock3} /><StatCard label="Dominadas" value={general.mastered} detail={`${general.favorite} favoritas`} icon={Trophy} /><StatCard label="Sin ver" value={general.unseen} detail={`${general.seen} preguntas vistas`} icon={ArrowDownUp} /></section><Tabs defaultValue="chapters" className="w-full"><TabsList className="grid h-auto w-full grid-cols-2 sm:grid-cols-4"><TabsTrigger value="chapters">Capítulos</TabsTrigger><TabsTrigger value="types">Tipos</TabsTrigger><TabsTrigger value="levels">Dificultad</TabsTrigger><TabsTrigger value="sources">Fuentes</TabsTrigger></TabsList><TabsContent value="chapters"><MetricTable title="Rendimiento por capítulo" description="Ordenado de peor a mejor." rows={statistics.chapters} extraHeader="Capítulo" /></TabsContent><TabsContent value="types"><MetricTable title="Rendimiento por tipo" description="Los tipos que más necesitan repetición aparecen primero." rows={statistics.types} extraHeader="Tipo" /></TabsContent><TabsContent value="levels"><MetricTable title="Rendimiento por dificultad" description="Compara la presión real de cada nivel." rows={statistics.difficulties} extraHeader="Dificultad" /></TabsContent><TabsContent value="sources"><MetricTable title="Rendimiento por fuente" description="Daniel y Profetas y Reyes por separado." rows={statistics.sources} extraHeader="Fuente" /></TabsContent></Tabs><section className="grid gap-4 lg:grid-cols-2"><WeakCard title="Capítulos con menor precisión" rows={statistics.weakChapters} /><WeakCard title="Tipos con menor precisión" rows={statistics.weakTypes} /></section></div>
}

function MetricTable({ title, description, rows, extraHeader }: { title: string; description: string; rows: { key: string; label: string; total: number; accuracy: number; averageResponseTimeMs: number; incorrect: number; mastery: number }[]; extraHeader: string }) {
  return <Card className="mt-4 shadow-none"><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>{extraHeader}</TableHead><TableHead>Respondidas</TableHead><TableHead>Precisión</TableHead><TableHead>Tiempo promedio</TableHead><TableHead>Fallos</TableHead><TableHead>Dominio</TableHead></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.key}><TableCell className="font-medium">{row.label}</TableCell><TableCell>{row.total}</TableCell><TableCell><span className={row.accuracy < 70 ? "font-semibold text-destructive" : ""}>{row.accuracy}%</span></TableCell><TableCell>{formatElapsedMs(row.averageResponseTimeMs)}</TableCell><TableCell>{row.incorrect}</TableCell><TableCell><Badge variant={row.mastery >= 4 ? "default" : "secondary"}>{row.mastery}/5</Badge></TableCell></TableRow>)}{rows.length === 0 ? <TableRow><TableCell colSpan={6} className="h-24 text-center text-muted-foreground">Sin datos todavía.</TableCell></TableRow> : null}</TableBody></Table></div></CardContent></Card>
}

function WeakCard({ title, rows }: { title: string; rows: { key: string; label: string; accuracy: number; incorrect: number }[] }) {
  return <Card className="shadow-none"><CardHeader><CardTitle className="text-base">{title}</CardTitle><CardDescription>Prioriza los tres primeros.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3">{rows.map((row, index) => <div key={row.key} className="flex items-center gap-3"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-semibold">{index + 1}</span><span className="min-w-0 flex-1 truncate text-sm font-medium">{row.label}</span><span className="text-sm font-semibold text-destructive">{row.accuracy}%</span><span className="text-xs text-muted-foreground">{row.incorrect} fallos</span></div>)}{rows.length === 0 ? <p className="text-sm text-muted-foreground">Aparecerán después de tus primeras respuestas.</p> : null}</CardContent></Card>
}
